"""Embed shaders/*.hlsl into a C header so the DLL carries its own filters.

The same files stay on disk: a copy in the game's shaders/ folder overrides the built-in
one of the same name, which is how a filter can be edited without rebuilding.

Usage: python3 tools/embed_shaders.py            (regenerates src/core/shader_sources.h)
"""
import pathlib, re, sys

root = pathlib.Path(__file__).resolve().parent.parent
out = root / "src" / "core" / "shader_sources.h"
files = sorted((root / "shaders").glob("*.hlsl"))

def escape(line):
    return line.replace("\\", "\\\\").replace('"', '\\"')

parts = ['/* Generated by tools/embed_shaders.py -- do not edit. */\n',
         "struct EmbeddedShader { const char* name; int scale; const char* source; };\n",
         "static const struct EmbeddedShader embedded_shaders[] = {\n"]
for f in files:
    text = f.read_text(encoding="utf-8")
    m = re.search(r"^//!\s*scale\s+(\d+)\s*$", text, re.M)
    scale = int(m.group(1)) if m else 0
    parts.append('    { "%s", %d,\n' % (f.stem, scale))
    for line in text.splitlines():
        parts.append('        "%s\\n"\n' % escape(line))
    parts.append("    },\n")
parts.append("};\n")
out.write_text("".join(parts), encoding="utf-8")
print("%s: %d shader(s), %d bytes" % (out.relative_to(root), len(files), out.stat().st_size))
